config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, only: [:create, :destroy, :new]
  end
  # Defines the root path route ("/")
   root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, presence: true
    belongs_to :user, optional: true
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, presence: true
    validates :body, presence: true

    belongs_to :user
    has_many :comments, dependent: :destroy

    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post

    def new
        @comment = @post.comments.new
    end

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        @comment.user = current_user
        if @comment.save
        redirect_to @post, notice: "Comment was successfully created"
        else
        redirect_to @post, alert: "Comment was not created"
        end
    end
    
    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to @post, notice: "Comment was successfully deleted"
    end
    
    private
    
    def comment_params
        params.require(:comment).permit(:content)
    end
    
    def set_post
        @post = Post.find(params[:post_id])
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, except: [:index, :new, :create]
  

  def index
    @posts = Post.includes(:comments).order(created_at: :desc)
    @pagy, @posts = pagy(@posts)
  end

  def show
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: "Post was successfully created"
    else
      render :new , status: :unprocessable_entity

    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit , status: :unprocessable_entity
    end
  end

  def destroy
      @post.destroy
      redirect_to root_path
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.includes(:comments).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, post.comments.build], local: true) do |form| %>
    <% if form.object.errors.any? %>
      <div>
          <% form.object.errors.full_messages.each do |msg| %>
             <div> <%= msg %> </div>
          <% end %>
      </div>
    <% end %>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3pV0n4W3eKj2SAG29LPbBE6UbQXVDJS5p4laSSRxZI6n1tCh1bAqeIhsKo" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", media: "all" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="/">My Blog</a>
        <div class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <a class="nav-item nav-link" href="<%= new_post_path %>">New post</a>
            <a class="nav-item nav-link" href="<%= edit_user_registration_path %>">Profile</a>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-link nav-item nav-link' %>
          <% else %>
            <a class="nav-item nav-link" href="<%= new_user_session_path %>">Log in</a>
            <a class="nav-item nav-link" href="<%= new_user_registration_path %>">Sign up</a>
          <% end %>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container mt-5">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-pzjw8f+ua7Kw1TIq5z8pvK2BRi6LfuDAK67U2CXM/6zO2y4MIMF86W43v43R5pMn" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgQP6xGChxK7EEX57IcKMdz6a1Fj/uj0CSK/UzGzsBOeX9uA5e8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, html: { multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1> edit blog post </h1>

<%= render partial: 'form', locals: {post: @post} %>

<%= button_to "delete", @post, method: :delete, data: {turbo_confirm: "Tem certeza?"}  %>

app/views/posts/index.html.erb
<h1 class="text-center my-4">MY <span class="text-primary">BLOG</span></h1>


<div class="container">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title"><%= post.title %></h5>
          </div>
          <% if post.image? %>
            <%= image_tag post.image.url, class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">Publicado às <%= post.created_at.strftime("%H:%M") %></h6>
            <p class="card-text"><%= truncate(post.body, length: 100) %></p>
            <%= link_to 'Ver Comentários', post, class: 'btn btn-primary mt-3 d-block' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/posts/new.html.erb
<h1 class="my-4">New Blog Post</h1>

<%= render partial: 'form', locals: { post: @post } %>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="card mb-4 shadow-sm">
    <% if @post.image? %>
      <%= image_tag @post.image.url, class: "card-img-top" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= @post.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Publicado às <%= @post.created_at.strftime("%H:%M") %> por <%= @post.user.email %></h6>
      <p class="card-text"><%= @post.body %></p>
    </div>
  </div>

  <h3>Comentários</h3>
  <% @post.comments.each do |comment| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= comment.user.email %></h5>
        <p class="card-text"><%= comment.body %></p>
        <% if comment.image? %>
          <%= image_tag comment.image.url, class: "img-fluid mt-3" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= form_with(model: [@post, @post.comments.build], local: true) do |form| %>
    <div class="form-group">
      <%= form.label :body, "Adicionar Comentário" %>
      <%= form.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :image, "Anexar Imagem" %>
      <%= form.file_field :image, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <%= form.submit "Postar Comentário", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>